urls:
  listings: 'https://data.insideairbnb.com/united-states/ca/los-angeles/2024-03-11/visualisations/listings.csv'
  crimes: 'https://data.lacity.org/resource/2nrs-mtv8.csv'
  comments: 'https://data.insideairbnb.com/united-states/ca/los-angeles/2024-06-07/data/reviews.csv.gz'
read_adls_container_paths:
  bronze:
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Bronze/listings/'
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Bronze/crimes/'
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Bronze/comments/'
write_adls_container_paths:
  bronze:
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Bronze/'
  silver:
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Silver/listings/'
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Silver/crimes/'
    - 'abfss://mydata@modulosparkmasterucm.dfs.core.windows.net/tfm/Files/Silver/comments/'
google_key:
  api_key: 'api-key'